{{- if .Values.Master.HostName }}
apiVersion: {{ .Values.Master.Ingress.ApiVersion }}
kind: Ingress
metadata:
  annotations:
    {{- if .tls }}
    ingress.kubernetes.io/secure-backends: "true"
    {{- end }}
    {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  name: {{ template "jenkins.fullname" . }}
spec:
  rules:
  - host: {{ .Values.Master.HostName | quote }}
    http:
      paths:
        - path: {{ default "/" .path }}
          backend:
            serviceName: {{ template "jenkins.fullname" . }}
            servicePort: {{ .Values.Master.ServicePort }}
{{- if .tls }}
  tls:
  - hosts:
    - {{ .name }}
    secretName: {{ .tlsSecret }}
{{- end }}
{{- end }}
